# Generated by Django 4.2.6 on 2023-11-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название статьи', max_length=50, verbose_name='Название')),
                ('text', models.TextField(help_text='Введите текст статьи', max_length=5000, verbose_name='Текст статьи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Блог',
                'ordering': ['created'],
            },
        ),
    ]
