# Generated by Django 4.2.6 on 2023-11-24 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Превью поста'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(help_text='Введите название статьи', max_length=15000, verbose_name='Название'),
        ),
    ]
