# Generated by Django 4.2.6 on 2023-11-25 12:52

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_thumbnail_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Название'),
        ),
    ]
