# Generated by Django 4.2.6 on 2023-11-27 07:37

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_article_thumbnail_alter_article_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Блог'},
        ),
        migrations.AddField(
            model_name='article',
            name='short_descr',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Введите краткое описание статьи', max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', max_length=10, verbose_name='Статус поста'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='static/img/blog/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Превью поста'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Введите основной текст статьи', max_length=15000, verbose_name='Текст'),
        ),
    ]
