# Generated by Django 4.2.6 on 2024-10-03 14:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_article_short_descr_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(help_text='Введите основной текст статьи', max_length=15000, verbose_name='Текст'),
        ),
    ]
