# Generated by Django 4.2.6 on 2024-03-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
