# Generated by Django 4.2.6 on 2024-02-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название товара')),
                ('article_num', models.CharField(max_length=50, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена товара')),
                ('main_image', models.ImageField(null=True, upload_to='img/products', verbose_name='Основное изображение товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('age', models.CharField(default=0, max_length=2, verbose_name='Возрастное ограничение')),
                ('elements', models.IntegerField(blank=True, default=0, help_text='Укажите число кол-ва деталей', null=True, verbose_name='Количество деталей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Наличие')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text="Введите категорию группы 'Товары Лего'", max_length=64, verbose_name="Группа товаров 'Lego'")),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Введите название коллекции', max_length=64, verbose_name='Коллекция конструктора')),
            ],
            options={
                'verbose_name': 'Коллекция конструктора',
                'verbose_name_plural': 'Коллекции конструкторов',
            },
        ),
        migrations.CreateModel(
            name='ProductEducations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text="Введите категорию группы 'Educations'", max_length=64, verbose_name="Группа товаров 'Educations'")),
            ],
            options={
                'verbose_name': "Группа товаров 'Educations'",
                'verbose_name_plural': "Группы товаров 'Educations'",
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/products', verbose_name='Изображение товара')),
                ('is_active', models.BooleanField(default=True, verbose_name='Наличие изображений')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_no_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Начальная цена')),
                ('discount_active', models.BooleanField(default=False, verbose_name='Активность скидки')),
                ('discount', models.IntegerField(default=10, help_text='Укажите % скидки', verbose_name='Скидка')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена товара')),
                ('product', models.ForeignKey(blank=True, default=None, help_text='Выберите товар', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар со скидкой',
                'verbose_name_plural': 'Товары со скидкой',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=None, help_text='Выберите категорию товара', on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='Категория товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_сollection',
            field=models.ForeignKey(blank=True, default=None, help_text='Выберите Коллекцию', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcollection', verbose_name='Коллекция'),
        ),
    ]
