# Generated by Django 4.2.6 on 2024-02-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='productcollection',
            options={'verbose_name': 'Коллекция товара', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='article_num',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена товара'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default=None, help_text='Введите категорию товара', max_length=64, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='name',
            field=models.CharField(default=None, help_text='Введите название коллекции', max_length=64, verbose_name='Коллекция товара'),
        ),
    ]
