# Generated by Django 4.2.6 on 2024-02-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price_alter_product_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='productcollection',
            options={'ordering': ['name'], 'verbose_name': 'Коллекция товара', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'ordering': ['discount'], 'verbose_name': 'Товар со скидкой', 'verbose_name_plural': 'Товары со скидкой'},
        ),
        migrations.AlterModelOptions(
            name='producteducations',
            options={'ordering': ['name'], 'verbose_name': "Группа товаров 'Educations'", 'verbose_name_plural': "Группы товаров 'Educations'"},
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.IntegerField(default=0, max_length=20, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена с учетом скидки', max_digits=10, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount',
            field=models.IntegerField(default=0, help_text='Укажите % скидки', verbose_name='Скидка %'),
        ),
    ]
