# Generated by Django 4.2.6 on 2024-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность скидки'),
        ),
    ]
