# Generated by Django 4.2.6 on 2024-03-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_wishlist_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdiscount',
            old_name='total_price',
            new_name='discount_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена с учетом скидки', max_digits=10, verbose_name='Итоговая цена'),
        ),
    ]
