# Generated by Django 4.2.6 on 2024-03-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_discount_discount_active_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_сollection',
        ),
        migrations.AddField(
            model_name='product',
            name='сollection',
            field=models.CharField(choices=[('AVATAR', 'Avatar'), ('DC', 'Dc')], default=None, help_text='Выберите Коллекцию', max_length=25, verbose_name='Коллекция'),
        ),
        migrations.DeleteModel(
            name='ProductCollection',
        ),
    ]
