# Generated by Django 4.2.6 on 2024-03-26 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_remove_product_product_category_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CONSTRUCTOR', 'Конструктор'), ('ACCESSORIES', 'Аксессуары'), ('BOOKS', 'Книги и журналы')], default=None, help_text='Выберите Категорию', max_length=25, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='сollection',
            field=models.CharField(choices=[('AVATAR', 'Avatar'), ('DC', 'DC')], help_text='Выберите Коллекцию', max_length=25, verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
