# Generated by Django 4.2.6 on 2024-04-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_age_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возрастное ограничение'),
        ),
    ]
