# Generated by Django 4.2.6 on 2024-05-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='сollection',
            field=models.CharField(choices=[('AVATAR', 'Avatar'), ('DC', 'DC'), ('MARVEL', 'Marvel'), ('INDIANA JONES', 'Indiana Jones'), ('ICONS', 'Icons'), ('JURASSIC WORLD', 'Jurassic World')], help_text='Выберите Коллекцию', max_length=25, verbose_name='Коллекция'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
