# Generated by Django 4.2.6 on 2024-05-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_price_alter_product_сollection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='сollection',
            new_name='collection',
        ),
    ]
