# Generated by Django 4.2.6 on 2024-08-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('AVATAR', 'Avatar'), ('DC', 'DC'), ('MARVEL', 'Marvel'), ('INDIANA JONES', 'Indiana Jones'), ('ICONS', 'Icons'), ('JURASSIC WORLD', 'Jurassic World'), ('FRIENDS', 'Friends'), ('CITY', 'City')], help_text='Выберите Коллекцию', max_length=25, verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена с учетом скидки', max_digits=7, verbose_name='Скидочная цена'),
        ),
    ]
