# Generated by Django 4.2.6 on 2024-08-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_collection_alter_product_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CONSTRUCTOR', 'Конструктор'), ('ACCESSORIES', 'Аксессуары'), ('Книги и журналы', 'Books')], default=None, help_text='Выберите Категорию', max_length=25, verbose_name='Категория'),
        ),
    ]
